# Default values for node-Version.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

image:
  repository: jfrogtraining-docker-dev.jfrog.io/node-version
  tag: latest
  pullPolicy: Always

imageCredentials:
  registry: docker.artifactory
  username: admin
  password: password

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: LoadBalancer
  port: 3000
  nodePort: ""

resources: {}

nodeSelector: {}