# Default values for node-Version.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

image:
  repository: jainishshah17/node-version
  secretName: regsecret
  tag: latest
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: LoadBalancer
  port: 3000
  nodePort: ""

resources: {}

nodeSelector: {}