apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "node-version.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "node-version.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "node-version.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "node-version.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
